export const FONTS = [
  "Meanwhile",
  "MORELOVE",
  "PINK ROSE",
  "RAINBOWDREAMS",
  "REALITY",
  "SCRIBBLE",
  "SOMEKIND",
  "SQUISHY",
  "Summershine",
  "Sunshine",
  "SweetDreams",
  "TheWildOne",
  "TheWildOneFun",
  "TheWildOneSolid",
  "Asteroid",
  "BeachBikini",
  "Beachside",
  "BeachSunrise",
  "BlueberryMuffin",
  "Cakepop",
  "California",
  "DearMay",
  "Firefly",
  "Forever",
  "FreshLemonade",
  "Frozen",
  "Hathway",
  "HeySugar",
  "Honey",
  "Honeycomb",
  "However",
  "IceCream",
  "Jade Skies",
  "Joyful",
  "Love Hearts",
  "Love More",
  "Love Vibes",
  "LoveAndHoney",
  "MapleSugar",
  "Thinker",
  "Thoughtful",
  "TigerLand",
  "Tigerlily",
];



export const fontMap = {
  Meanwhile: "Meanwhile",
  MONKEY: "Monkey",
  MORELOVE: "MoreLove",
  "PINK ROSE": "Pink Rose",
  RAINBOWDREAMS: "RainbowDreams",
  REALITY: "Reality",
  SCRIBBLE: "Scramble",
  SOMEKIND: "Somekind",
  SQUISHY: "SourSlushy",
  Summershine: "SummerSunshine",
  Sunshine: "Sunlight",
  SweetDreams: "SweetDreams",
  TheWildOne: "TheWildOne",
  TheWildOneFun: "TheWildOneFun",
  TheWildOneSolid: "TheWildOneSolid",
  Asteroid: "Asteroid",
  BeachBikini: "BeachBikini",
  Beachside: "Beachside",
  BeachSunrise: "BeachSunrise",
  BlueberryMuffin: "BlueberryMuffin",
  Cakepop: "Cakepop",
  California: "California",
  DearMay: "DearMay",
  Firefly: "Firefly",
  Forever: "Forever",
  FreshLemonade: "FreshLemonade",
  Frozen: "Frozen",
  Hathway: "Hathway",
  HeySugar: "HeySugar",
  Honey: "Honey",
  Honeycomb: "Honeycomb",
  However: "However",
  IceCream: "IceCream",
  "Jade Skies": "Jade Skies",
  Joyful: "Joyful",
  "Love Hearts": "Love Hearts",
  "Love More": "Love More",
  "Love Vibes": "Love Vibes",
  LoveAndHoney: "LoveAndHoney",
  MapleSugar: "MapleSugar",
  Thinker: "Thinker",
  Thoughtful: "Thoughtful",
  TigerLand: "TigerLand",
  Tigerlily: "Tigerlily",
};


export const COLORS = [
  "#FFFFFF",
  "#000000",
  "#f44336",
  "#e91e63",
  "#9c27b0",
  "#3f51b5",
  "#2196f3",
  "#03a9f4",
  "#00bcd4",
  "#009688",
  "#4caf50",
  "#8bc34a",
  "#cddc39",
  "#ffeb3b",
  "#ffc107",
  "#ff9800",
  "#ff5722",
  "#795548",
  "#607d8b",
  "#ff5252",
  "#ff4081",
  "#e040fb",
  "#7c4dff",
  "#536dfe",
  "#448aff",
  "#40c4ff",
  "#18ffff",
  "#64ffda",
  "#69f0ae",
  "#b2ff59",
  "#eeff41",
  "#ffff00",
  "#ffd740",
  "#ffab40",
  "#ff6e40",
];


export const SIZES = [10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32];