import Footer from "@/features/footer/Footer";
import "./globals.css";
import Navbar from "@/features/Main/Navbar/Navbar";
import RecaptchaProvider from "@/features/signup/recaptcha/RecaptchaProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600&family=Montserrat:wght@500;700&family=Raleway:wght@500&family=Rubik:wght@500;700&family=Nunito:wght@600&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        <RecaptchaProvider>
        <Navbar/>
        {children}
        <Footer />
        </RecaptchaProvider>
        </body>
    </html>
  );
}
